### ISSUE TITLE
grpc fails to build for indigo due to requiring too new a version of cmake

### ISSUE THREAD

**Issue by tfoote** [CogRob/catkin_grpc#3]
It's asking for 3.1.0 or higher but trusty only has 2.8.12.2

http://build.ros.org/view/Ibin_uT64/job/Ibin_uT64__grpc__ubuntu_trusty_amd64__binary/1/console

https://github.com/ros/rosdistro/pull/15867

```
11:53:12  debian/rules build
11:53:12 dh  build
11:53:12    dh_testdir
11:53:13 Unknown option: buildsystem
11:53:13 dh_testdir: warning: ignored unknown options in DH_OPTIONS
11:53:13    debian/rules override_dh_auto_configure
11:53:13 make[1]: Entering directory `/tmp/binarydeb/ros-indigo-grpc-0.0.1'
11:53:13 # In case we're installing to a non-standard location, look for a setup.sh
11:53:13 # in the install tree that was dropped by catkin, and source it.  It will
11:53:13 # set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
11:53:13 if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi && \
11:53:13 	dh_auto_configure -- \
11:53:13 		-DCATKIN_BUILD_BINARY_PACKAGE="1" \
11:53:13 		-DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
11:53:13 		-DCMAKE_PREFIX_PATH="/opt/ros/indigo"
11:53:13 	mkdir -p obj-x86_64-linux-gnu
11:53:13 	cd obj-x86_64-linux-gnu
11:53:13 	cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo -DCMAKE_PREFIX_PATH=/opt/ros/indigo
11:53:13 CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
11:53:13   CMake 3.1.0 or higher is required.  You are running version 2.8.12.2
11:53:13 
11:53:13 
11:53:13 -- Configuring incomplete, errors occurred!
11:53:13 dh_auto_configure: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo -DCMAKE_PREFIX_PATH=/opt/ros/indigo returned exit code 1
11:53:13 make[1]: *** [override_dh_auto_configure] Error 2
11:53:13 make[1]: Leaving directory `/tmp/binarydeb/ros-indigo-grpc-0.0.1'
11:53:13 make: *** [build] Error 2
11:53:13 dpkg-buildpackage: error: debian/rules build gave error exit status 2
11:53:13 E: Building failed
11:53:13 Traceback (most recent call last):
11:53:13   File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 133, in build_binarydeb
11:53:13     subprocess.check_call(cmd, cwd=source_dir)
11:53:13   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
11:53:13     raise CalledProcessError(retcode, cmd)
11:53:13 subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-indigo-grpc']' returned non-zero exit status 1
11:53:13 # END SUBSECTION```

**Comment by BillWSY** [comment]
Fixed http://build.ros.org/job/Idev__grpc__ubuntu_trusty_amd64/3/display/redirect?page=changes
